#!/bin/bash

_script_dir="$HOME/.git_run_local.d"

list_actions() {
    local field_separator="$1"

    if [ -d "$_script_dir" ]; then
        for i in "$_script_dir"/*;do
            if [ -x "$i" ]; then
                echo -n -e "${field_separator}$(basename "$i")"
            fi
        done
    fi
}

if [ "$1" == "--autocomplete" ]; then
    list_actions "\n"
    exit 0
fi

if [ $# -eq 0 ]; then
    echo -n "Local actions:"
    list_actions " "
    echo ""
    exit 0
fi

if [ -x "$_script_dir"/"$1" ]; then
    _script="$1"
    shift
    _repository_dir="$(git rev-parse --show-toplevel)"
    _ret=$?
    if [ $_ret -ne 0 ]; then
        exit $_ret
    fi
    REPOSITORY_PATH="$_repository_dir" "$_script_dir"/"$_script" "$@"
else
    echo "Local action '$1' not defined."
    exit 1
fi
