#!/bin/bash

repository_dir="$(git rev-parse --show-toplevel)"
script_dir="$HOME/.git_run_local.d"

list_actions() {
    local field_separator="$1"

    if [ -d "$script_dir" ]; then
        for i in "$script_dir"/*;do
            if [ -x "$i" ]; then
                echo -n -e "${field_separator}$(basename "$i")"
            fi
        done
    fi
}

if [ "$1" == "--autocomplete" ]; then
    list_actions "\n"
    exit 0
fi

if [ $# -eq 0 ]; then
    echo -n "Local actions:"
    list_actions " "
    echo ""
    exit 0
fi

if [ -x "$script_dir"/"$1" ]; then
    script="$1"
    shift
    REPOSITORY_PATH="$repository_dir" "$script_dir"/"$script" "$@"
else
    echo "Local action '$1' not defined."
    exit 1
fi
