#!/bin/bash

SCRIPTPATH="$(dirname "`readlink -f $0`")"
source "$SCRIPTPATH/common.sh" || exit 1

load_config
check_config EDITOR NOTEFILE="$HOME/notes.txt"
need_binaries $EDITOR gawk less

AWK_SCRIPT="$SCRIPTPATH/notes.awk"

if [ ! -e "$AWK_SCRIPT" ]; then
    echo "Critical helper script $AWK_SCRIPT missing."
    exit 2
fi

if [ $# -gt 0 ]; then
    c=""
    if [ "$1" == "-i" ]; then
        c="-i"
        shift
    fi

    if [ "$1" == "--autocomplete" ]; then
        shift
        if [ $# -gt 0 ]; then
            search="$*"
            grep --color=never --only-matching -- "${search}.*" "$NOTEFILE" | sed -e 's/\$/\\\$/g'
        fi
        exit 0
    fi
    if [ "$1" == "--autocomplete-remove" ]; then
        shift
        prefix=""
        if [ "$1" == "--prefix" ]; then
            shift
            prefix="$1"
            shift
        fi
        if [ $# -gt 0 ]; then
            search="$*"
            grep --color=never --only-matching -- "${search}.*" "$NOTEFILE" | sed -e "s/^$search/$prefix/" -e 's/\$/\\\$/g'
        fi
        exit 0
    fi

    if [ $# -eq 0 ]; then
        echo "Provide grep string."
        exit 1
    fi

    case "$1" in
        +*)
            search="${@}"
            search="${search:1}"
            if [ -z "$search" ]; then
                echo "Provide search string."
                exit 1
            fi

            pipeless="less -X -F"
            gawk -f "$AWK_SCRIPT" -v search="$search" "$NOTEFILE" | $pipeless
            ;;
        *)
            grep --color $c "$*" "$NOTEFILE"
            ;;
    esac
else
    exec $EDITOR "$NOTEFILE"
fi
