#!/bin/bash

IDENTIFIER="sdk-event-action-$USER"
IDENTIFIER_PID="/tmp/$IDENTIFIER-pid"

if [ $# -lt 1 ]; then
    echo "Usage: $(basename $0) <command to run in sdk>"
    echo "       $(basename $0) quit        - Stop the server-sdk"
    exit 1
fi

if [ ! -e "$IDENTIFIER_PID" ]; then
    echo "SDK server doesn't seem to be running."
    exit 1
fi

ps -p $(cat $IDENTIFIER_PID) >/dev/null

if [ ! $? -eq 0 ]; then
    echo "SDK server doesn't seem to be running. (stale pid file)"
    exit 1
fi

if [ "$1" == "quit" ]; then
    kill -s SIGUSR2 "$(cat $IDENTIFIER_PID)"
    exit 0
fi

for i in $(seq 0 99); do
    Q="/tmp/$IDENTIFIER-$i"
    if [ -e "$Q" ]; then
        continue
    fi

    echo "$PWD" > $Q-dir
    echo "$@" > $Q
    kill -s SIGUSR1 "$(cat $IDENTIFIER_PID)"
    exit 0
done

# We get here if none of 100 slots above were available
echo "SDK queue full."
exit 2
