#!/bin/bash

TOUCHPAD_DEVICE_NAME=touchpad\ synaptics

touchpad_id=
for name in $TOUCHPAD_DEVICE_NAME; do
    touchpad_id=$(xinput list | grep -i "$name" | sed -e 's/.*id=\([0-9]*\).*/\1/')
    if [ -n "$touchpad_id" ]; then
        break
    fi
done

if [ -z "$touchpad_id" ]; then
    echo "No touchpad device detected."
    exit 1
fi

current_state=$(xinput list-props $touchpad_id | grep "Device Enabled" | awk '{ print $4 }')

new_state="enable"
if [ $current_state -eq 1 ]; then
    new_state="disable"
fi

xinput $new_state $touchpad_id
echo "Touchpad ${new_state}d."
