#!/bin/bash

declare -i ID
ID=`xinput list | grep -Eo 'TouchPad\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`
declare -i STATE
STATE=`xinput list-props $ID | grep 'Device Enabled' | awk '{print $4}'`
NEW_STATE="enable"
if [ $STATE -eq 1 ]; then
    NEW_STATE="disable"
fi
xinput $NEW_STATE $ID
echo "Touchpad ${NEW_STATE}d."
