#!/bin/bash

# v5:
#   - Add -s|--scripts option to only run extra scripts from upload-pubkey.d
#     directory. Add bash autocompletion support.
#
# v4:
#   - Default values for variables are read from $HOME/.config/upload-pubkey
#     file if the file exists.
#
# v3:
#   - Add possibility to execute user defined scripts after uploading keys
#     If executable files are found in $HOME/.config/upload-pubkey.d directory
#     they are all executed (in random order) if key upload was successful.
#     This can be used for example to set target environment properly, etc.
#     When the scripts are executed the environment will contain values in
#     variables USE_KEY, USE_USER, USE_HOST, SSH_OPT as defined when uploading
#     the keys.
#
# v2:
#   - use sshpass if available so that password needs to be typed only once
#   - provide the password to devel-su from stdin to avoid visible password

SCRIPT_VERSION=5
DEFAULT_KEY="$HOME/.ssh/id_rsa.pub"
DEFAULT_USER="nemo"
DEFAULT_HOST="192.168.2.15"
DEFAULT_CONFIG="$HOME/.config/upload-pubkey"
EXECUTE_D="$DEFAULT_CONFIG.d"

SSH_OPT="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
USE_KEY="$DEFAULT_KEY"
USE_USER="$DEFAULT_USER"
USE_HOST="$DEFAULT_HOST"
USE_SSHPASS="$(which sshpass)"

if [ -e "$DEFAULT_CONFIG" ]; then
    source "$DEFAULT_CONFIG"
fi

run_scripts() {
    if [ -d "$EXECUTE_D" ]; then
        for i in $(ls -1 "$EXECUTE_D" | sort); do
            script="$EXECUTE_D/$i"
            if [ -x "$script" ]; then
                USE_KEY="$USE_KEY" USE_USER="$USE_USER" USE_HOST="$USE_HOST" SSH_OPT="$SSH_OPT" $script
            fi
        done
    fi
}

while [ $# -gt 0 ]; do
    case "$1" in
        -v|--version)
            echo "$(basename $0) v$SCRIPT_VERSION"
            exit 0
            ;;
        --autocomplete)
            echo "-v --version -k --key -h --host -u --user -s --scripts"
            exit 0
            ;;
        -k|--key)
            shift
            if [ $# -lt 1 ]; then
                echo "Parameter missing for pubkey."
                exit 1
            fi
            USE_KEY="$1"
            ;;
        -h|--host)
            shift
            if [ $# -lt 1 ]; then
                echo "Parameter missing for host."
                exit 1
            fi
            USE_HOST="$1"
            ;;
        -u|--user)
            shift
            if [ $# -lt 1 ]; then
                echo "Parameter missing for user."
                exit 1
            fi
            USE_USER="$1"
            ;;
        -s|--scripts)
            run_scripts
            exit 0
            ;;
    esac

    shift
done

if [ ! -f "$USE_KEY" ]; then
    echo "Key \"$USE_KEY\" not found."
    exit 1
fi

SCRIPT="upload-pubkey-$(date +%s)$RANDOM.tmp"
SCRIPT_DATA=""
REMOTE_SCRIPT="/home/$USE_USER/.$SCRIPT"

finish() {
    unset SSHPASS
    unset SCRIPT_DATA
}

trap finish EXIT

INPUT_PASS=""
echo -n "($(basename $0)) $USE_USER@$USE_HOST's password: "
read -s SSHPASS
export SSHPASS

SCRIPT_DATA="#!/bin/bash
#PASSW $SSHPASS
mkdir -p ~/.ssh
echo \"$(cat $USE_KEY)\" >> ~/.ssh/authorized_keys
chmod -R go-rwx ~/.ssh"

if [ ! -z "$USE_SSHPASS" ]; then
    INPUT_PASS="$USE_SSHPASS -e"
else
    echo -e "\nRetype password..."
fi

echo -e "$SCRIPT_DATA" | $INPUT_PASS ssh $SSH_OPT $USE_USER@$USE_HOST "cat > $REMOTE_SCRIPT ; bash $REMOTE_SCRIPT ; grep \#PASSW $REMOTE_SCRIPT | cut -b8- | devel-su -c bash $REMOTE_SCRIPT 2>/dev/null ; rm -f $REMOTE_SCRIPT"

if [ $? -eq 0 ]; then
    run_scripts
    echo "done."
fi
